import React from "react";
import styles from "./services.module.css";

export default function Services() {
  const services = [
    {
      title: "Solar Photovoltaic(PV) Systems",
      des: "These systems convert sunlight directly into electricity using solar panels composed of photovoltaic cells. PV systems can be installed on rooftops, ground-mounted arrays, or integrated into building facades.",
    },
    {
      title: "Industrial and Commercial",
      des: "Solarian Astra commercial solar rooftop solutions are best suited for all businesses of all sizes and industries, including corporate offices, factories, warehouses, shoppingmalls, hospitals, hotels and more",
    },
    {
      title: "Residential Solar",
      des: "SAPL can turn your rooftop space into a power generating unit that can help you save an energy bills. SAPL provides an end-to-end consultancy and solutioning wherein our team of experts pro- fessionals conduct a detailed site survey and customise solutions basis individual customers needs",
    },
    {
      title: "Solar Lighting",
      des: "Solar-powered lighting systems utilize photovoltaic cells to charge batteries during the day, which then power LED lights at night. These systems are often used for outdoor lighting in residential, commercial, and public spaces.",
    },
    {
      title: "Offgrid Solar Systems",
      des: "Off-grid solar systems, also known as standalone systems, are not connected to the electrical grid. They typically include solar panels, batteries for energy storage, charge controllers, and inverters to provide electricity in remote areas or for backup power.",
    },
    {
      title: "Grid-Tied Solar Systems",
      des: "Grid-tied solar systems are connected to the electrical grid. Excess electricity generated by the solar panels can be fed back into the grid, often through net metering arrangements, allowing consumers to offset their electricity bills and contribute to renewable energy generation.",
    },
    {
      title: "Solar Energy Consulting and Financing",
      des: "Consulting firms provide expertiseon solar energy projects, includingfeasibility studies, system design,regulatory compliance, and finan-cial analysis. Financing optionssuch as solar leases, power pur-chase agreements (PPAs), andincentives may also be offered tofacilitate solar adoption.",
    },
    {
      title: "Solar Farm Development",
      des: "Large-scale solar farms consist of multiple solar panels or solar arrays installed on land or rooftops to generate electricity for utili- ty-scale power generation. These projects often involve site selec- tion, permitting, engineering, pro- curement, and construction (EPC) services.",
    },
    {
      title: "Solar Energy Education and Training",
      des: "Educational institutions, training centers, and online platforms offer courses and workshops on solar energy technology, installation, maintenance, and safety practices to professionals and enthusiasts entering the solar industry.",
    },
    {
      title: "Solar Panel Maintenance and Cleaning",
      des: "Regular maintenance and cleaning of solar panels are essential to ensure optimal performance and longevity. Services may include inspections, panel cleaning, and repairs to maximize energy production.",
    },
  ];
  return (
    <div className={` ${styles.Services}`}>
      <h2>Our Services</h2>
      <div className={`flex-col-center ${styles.servicesContainer}`}>
        {services?.map((item, idx) => (
          <div
            key={idx}
            className={`flex-col-center ${styles.singleContainer} ${
              idx == 2 || idx == 6 ? styles.mt : ""
            }`}
          >
            <p className={`txt1 ${styles.title}`}>{item.title}</p>
            <p className={styles.des}>{item.des}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
